db:
  image: postgres:9.4
  environment:
    - POSTGRES_USER=rinse-rss

web:
  build: .              # build using default Dockerfile
  command: python server.py run
  volumes:
    - .:/opt/rinse-rss  # mount current directory inside container
  links:
    - db
  environment:
    - SQLALCHEMY_DATABASE_URI=postgres://rinse-rss@db
  ports:
    - "5000:5000"


redis:
  image: redis

worker:
  build: .
  command: celery worker --app=tasks --beat --loglevel=debug
  volumes:
    - .:/opt/rinse-rss
  links:
    - redis
    - db
  environment:
    - C_FORCE_ROOT=TRUE
    - SQLALCHEMY_DATABASE_URI=postgres://rinse-rss@db
