dbdata:
  image: postgres:9
  volumes:
    - /var/lib/postgresql
  command: echo "This data-only container should exit immediately."

db:
  image: postgres:9
  volumes_from:
    - dbdata
  environment:
    POSTGRES_USER: rinse-rss

web:
  build: .
  links:
    - db
  environment:
    SQLALCHEMY_DATABASE_URI: "postgres://rinse-rss@db/rinse-rss"
  ports:
    - "5000:5000"
  command: python manage.py runserver

scrape:
  build: .
  links:
    - db
  environment:
    SQLALCHEMY_DATABASE_URI: "postgres://rinse-rss@db/rinse-rss"
  command: /bin/bash -c "while sleep 300; do python manage.py scrape; done"
