---
title: Rinse FM
subtitle: London's favorite pirate radio station.
description:
    "London's favorite pirate radio station now available in unofficial podcast format.

    Rinse FM is uniquely placed at the hub of the Capitalʼs thriving British underground music community, demonstrating throughout 18 years of broadcasting that they provide a vital, unique and exceptionally successful, grass-roots gateway into broadcast radio and the wider music industry.

    Rinseʼs DJs and MCs have won Mercury Music Prize awards, with nominations for numerous others, gold discs in recognition of sales, and widespread critical acclaim. In stark contrast to the homogenized radio landscape Rinse FM seeks to champion the diverse needs of young London and those passionate about youth-orientated music culture, currently showcasing genres typically referred to as Dubstep, UK Funky and Grime while interacting with and influencing those scenes. Rinseʼs fiercely grass-roots broadcasting ethos engages massively under-represented communities, especially 15-24 year olds."

keywords: "Rinse FM, rinse, grime, garage, dubstep, house, deep house, techno, urban, music"
category: Music     # http://www.apple.com/itunes/podcasts/specs.html#categories

owner: Rinse FM
copyright: "&#xA9; Rinse FM 2014"

language: en-gb

podcast_owner: Ben Jeffrey
podcast_owner_email: mail@benjeffrey.net

scrape_url: http://rinse.fm/podcasts/
url: http://rinse.fm/podcasts/

server_url: http://rinse.benjeffrey.net
thumbnail_url: http://rinse.benjeffrey.net/artwork
