---
- hosts: all
  vars:
    software_name: rinse-rss
  sudo: true
  tasks:
    - name: Git PPA is available
      apt_repository: repo="ppa:git-core/ppa" state=present
      notify:
        - ensure apt packages are up-to-date

    - name: Docker repository is available
      apt_repository: repo="deb http://get.docker.io/ubuntu docker main" state=present

    - name: Required packages are installed
      apt: name={{ item }} state=latest
      with_items:
        - lxc-docker
        - git
        - nginx
        - python-pip

    - name: Docker Compose is installed
      pip: name=docker-compose

    - name: Git repository is initialised
      command: git init /opt/{{ software_name }} creates=/opt/{{ software_name }}

    - name: Git repository configured to receive current branch in update mode
      command: git config --file /opt/{{ software_name }}/.git/config receive.denyCurrentBranch updateInstead

    - name: Git post-receive hook is present
      file: state=link src=/opt/{{ software_name }}/post-receive.githook dest=/opt/{{ software_name }}/.git/post-receive mode=a+x

    - name: Nginx reverse-proxy is configured
      file: state=link src=/opt/{{ software_name }}/nginx.conf dest=/etc/nginx/sites-enabled/{{ software_name }}
      notify:
        - restart Nginx

    - name: Upstart service is configured
      file: state=link src=/opt/{{ software_name }}/upstart.conf dest=/etc/init/{{ software_name }}.conf mode=u+rw,go+r
      notify:
        - reload Upstart configuration
        - restart service


  handlers:
    - name: ensure apt packages are up-to-date
      apt: update_cache=yes

    - name: restart Nginx
      service: name=nginx state=restarted

    - name: reload Upstart configuration
      command: initctl reload-configuration

    - name: restart service
      service: name={{ software_name }} state=restarted
