---
- hosts: all
  vars:
    software_name: rinse-rss
    server_name: rinse.benjeffrey.net
  remote_user: root
  tasks:
    - name: Docker repository key is installed
      apt_key: id=36A1D7869245C8950F966E92D8576A8BA88D21E9 keyserver=p80.pool.sks-keyservers.net
    - name: Docker repository is available
      apt_repository: repo="deb https://get.docker.com/ubuntu docker main" state=present

    - name: Required packages are installed
      apt: name={{ item }} state=latest
      with_items:
        - lxc-docker
        - nginx
        - python-pip

    - name: Docker Compose is installed
      pip: name=docker-compose

    - name: application files are copied over
      synchronize: src=../ dest=/opt/{{ software_name }} set_remote_user=no owner=no group=no delete=yes
      notify:
        - restart service

    - name: Nginx reverse-proxy is configured
      template: src=nginx.conf dest=/etc/nginx/sites-enabled/{{ software_name }}
      notify:
        - restart Nginx

    - name: Upstart service is configured
      template: src=upstart.conf dest=/etc/init/{{ software_name }}.conf mode=u+rw,go+r
      notify:
        - restart service

  handlers:
    - name: ensure apt packages are up-to-date
      apt: update_cache=yes

    - name: restart Nginx
      service: name=nginx state=restarted

    - name: restart service
      service: name={{ software_name }} state=restarted
