"""empty message

Revision ID: 17deb531074
Revises: None
Create Date: 2015-04-06 04:14:27.572802

"""

# revision identifiers, used by Alembic.
revision = '17deb531074'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_show',
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('web_url', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('slug')
    )
    op.create_table('individual_podcast',
    sa.Column('guid', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('broadcast_date', sa.DateTime(), nullable=True),
    sa.Column('web_url', sa.String(length=200), nullable=True),
    sa.Column('enclosure_url', sa.String(length=200), nullable=True),
    sa.Column('enclosure_content_length', sa.Integer(), nullable=True),
    sa.Column('enclosure_content_type', sa.String(length=100), nullable=True),
    sa.Column('show_slug', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['show_slug'], ['recurring_show.slug'], ),
    sa.PrimaryKeyConstraint('guid')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('individual_podcast')
    op.drop_table('recurring_show')
    ### end Alembic commands ###
