"""empty message

Revision ID: 46ccc3904cb
Revises: f47af812f0
Create Date: 2016-01-04 00:53:18.099356

"""

# revision identifiers, used by Alembic.
revision = '46ccc3904cb'
down_revision = 'f47af812f0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('show',
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('web_url', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('slug')
    )
    op.create_table('podcast_episode',
    sa.Column('guid', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('broadcast_datetime', sa.DateTime(), nullable=True),
    sa.Column('enclosure_url', sa.String(length=200), nullable=True),
    sa.Column('enclosure_content_length', sa.Integer(), nullable=True),
    sa.Column('enclosure_content_type', sa.String(length=100), nullable=True),
    sa.Column('show_slug', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['show_slug'], ['show.slug'], ),
    sa.PrimaryKeyConstraint('guid')
    )
    op.drop_table('individual_podcast')
    op.drop_table('recurring_show')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_show',
    sa.Column('slug', sa.VARCHAR(length=200), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('web_url', sa.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('slug')
    )
    op.create_table('individual_podcast',
    sa.Column('guid', sa.VARCHAR(length=200), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=True),
    sa.Column('broadcast_date', sa.DATETIME(), nullable=True),
    sa.Column('enclosure_url', sa.VARCHAR(length=200), nullable=True),
    sa.Column('enclosure_content_length', sa.INTEGER(), nullable=True),
    sa.Column('enclosure_content_type', sa.VARCHAR(length=100), nullable=True),
    sa.Column('show_slug', sa.VARCHAR(length=200), nullable=True),
    sa.ForeignKeyConstraint(['show_slug'], ['recurring_show.slug'], ),
    sa.PrimaryKeyConstraint('guid')
    )
    op.drop_table('podcast_episode')
    op.drop_table('show')
    ### end Alembic commands ###
