# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastEpisode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('broadcast_date', models.DateTimeField()),
                ('audio_url', models.URLField(unique=True)),
                ('audio_content_length', models.PositiveSmallIntegerField()),
                ('audio_content_type', models.CharField(max_length=200)),
            ],
        ),
    ]
