# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 17:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastEpisode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('broadcast_date', models.DateTimeField()),
                ('audio_url', models.URLField(unique=True)),
                ('audio_content_length', models.PositiveSmallIntegerField()),
                ('audio_content_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('url', models.URLField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='podcastepisode',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rinsefm.Show'),
        ),
    ]
