# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rinsefm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcastepisode',
            name='audio_content_length',
            field=models.PositiveIntegerField(),
        ),
    ]
